const Note = require("../models/Note");
const path = require("path");
const fs = require("fs");

// Import the upload configuration that handles different storage for files and thumbnails
const handleUpload = require("../config/uploadConfig");

// Ensure thumbnail directory exists
const ensureThumbnailDir = () => {
  const thumbnailDir = path.join(__dirname, "../uploads/thumbnails");
  if (!fs.existsSync(thumbnailDir)) {
    fs.mkdirSync(thumbnailDir, { recursive: true });
  }
};

// Get all notes (optionally by category)
const getNotes = async (req, res) => {
  try {
    const { category } = req.query;
    let query = {};
    if (category && category !== "All") query.category = category;

    const notes = await Note.find(query)
      .select("-file")
      .populate("uploadedBy", "username")
      .lean();

    const normalizedNotes = notes.map((noteObj) => {
      if (!noteObj.thumbnail || noteObj.thumbnail.endsWith("/default.png")) {
        noteObj.thumbnail = "/uploads/thumbnails/CNotes-Logo.png";
      }
      return noteObj;
    });
    res.status(200).json(normalizedNotes);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// Upload new note
const uploadNote = async (req, res) => {
  try {
    // Ensure thumbnail directory exists
    ensureThumbnailDir();

    if (!req.files?.file) {
      return res.status(400).json({ message: "No file uploaded" });
    }

    const file = req.files.file[0];
    const thumbnailFile = req.files.thumbnail?.[0];

    const noteData = {
      title: req.body.title,
      category: req.body.category,
      subject: req.body.subject || req.body.category,
      file: {
        data: file.buffer,
        contentType: file.mimetype,
        originalName: file.originalname,
        size: file.size,
      },
      uploadedBy: req.user.id,
      isGeneralNote: true, // All notes are now general category notes
    };

    // Handle thumbnail - store path to local file
    if (thumbnailFile && thumbnailFile.filename) {
      // thumbnailFile.filename contains the unique filename generated by the middleware
      noteData.thumbnail = `/uploads/thumbnails/${thumbnailFile.filename}`;
      console.log("Thumbnail saved:", noteData.thumbnail);
    } else {
      // Set default thumbnail if none provided
      noteData.thumbnail = "/uploads/thumbnails/CNotes-Logo.png";
      console.log("Using default thumbnail:", noteData.thumbnail);
    }

    const note = await Note.create(noteData);
    console.log("Note created successfully with ID:", note._id);
    res.status(201).json(note);
  } catch (error) {
    console.error("Upload error:", error);
    res
      .status(500)
      .json({ message: "Failed to upload note. Please try again." });
  }
};

// Download note file
const downloadNote = async (req, res) => {
  try {
    const note = await Note.findById(req.params.id);
    if (!note || !note.file?.data) {
      return res.status(404).json({ message: "Note or file not found" });
    }

    res.setHeader("Content-Type", note.file.contentType);
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="${note.file.originalName}"`,
    );

    res.send(note.file.data);
  } catch (error) {
    console.error("Download error:", error);
    res
      .status(500)
      .json({ message: "Failed to download note. Please try again." });
  }
};

// Delete note (admin only)
const deleteNote = async (req, res) => {
  try {
    const note = await Note.findById(req.params.id);
    if (!note) {
      return res.status(404).json({ message: "Note not found" });
    }

    // Delete thumbnail file if it exists
    if (
      note.thumbnail &&
      note.thumbnail !== "/uploads/thumbnails/CNotes-Logo.png"
    ) {
      const thumbnailPath = path.join(__dirname, "..", note.thumbnail);
      if (fs.existsSync(thumbnailPath)) {
        fs.unlinkSync(thumbnailPath);
      }
    }

    await Note.findByIdAndDelete(req.params.id);
    res.status(200).json({ message: "Note deleted successfully" });
  } catch (error) {
    console.error("Delete error:", error);
    res
      .status(500)
      .json({ message: "Failed to delete note. Please try again." });
  }
};

module.exports = {
  upload: handleUpload,
  getNotes,
  uploadNote,
  downloadNote,
  deleteNote,
};
